# Generated by Django 2.1.2 on 2018-11-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=15, unique=True)),
                ('imdbId', models.CharField(max_length=15)),
                ('tmdbId', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Movielens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=15, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('genres', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Omdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbid', models.CharField(max_length=15, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('pgr', models.CharField(max_length=10)),
                ('runtime', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('keywords', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('nvoters', models.IntegerField()),
                ('wrating', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=15, unique=True)),
                ('movieId', models.CharField(max_length=15)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('timestamp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=15, unique=True)),
                ('movieId', models.CharField(max_length=15)),
                ('tag', models.TextField()),
                ('timestamp', models.CharField(max_length=20)),
            ],
        ),
    ]
