# Generated by Django 2.1.2 on 2018-11-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvr', '0002_auto_20181102_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='userId',
            field=models.CharField(max_length=15),
        ),
    ]
